version: '3.8'

services:
  web:
    image: mi-appweb:latest  
    build:
      context: ./ 
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - db

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: miapp
      MYSQL_USER: usuario
      MYSQL_PASSWORD: pass
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql 
