version: '3.8'

services:
  web:
    image: khalifi11/mi-appweb:latest
    ports:
      - "3000:80"
    depends_on:
      - db
    restart: always

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: miapp
      MYSQL_USER: usuario
      MYSQL_PASSWORD: pass
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
