apiVersion: apps/v1
kind: Deployment
metadata:
  name: mi-appweb
  labels:
    app: mi-appweb
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mi-appweb
  template:
    metadata:
      labels:
        app: mi-appweb
    spec:
      containers:
        - name: mi-appweb
          image: khalifi11/mi-appweb:latest
          ports:
            - containerPort: 80
          env:
            - name: DB_HOST
              value: mi-app-db-service
            - name: DB_USER
              value: usuario
            - name: DB_PASSWORD
              value: pass
            - name: DB_NAME
              value: miapp
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
            requests:
              memory: "128Mi"
              cpu: "250m"

---

apiVersion: v1
kind: Service
metadata:
  name: mi-appweb-service
spec:
  selector:
    app: mi-appweb
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mi-app-db
  labels:
    app: mi-app-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mi-app-db
  template:
    metadata:
      labels:
        app: mi-app-db
    spec:
      containers:
        - name: mysql
          image: mysql:5.7
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: root
            - name: MYSQL_DATABASE
              value: miapp
            - name: MYSQL_USER
              value: usuario
            - name: MYSQL_PASSWORD
              value: pass
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql
            - name: mysql-initdb
              mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: mysql-data
          persistentVolumeClaim:
            claimName: mysql-pvc
        - name: mysql-initdb
          configMap:
            name: mysql-initdb-scripts

---

apiVersion: v1
kind: Service
metadata:
  name: mi-app-db-service
spec:
  selector:
    app: mi-app-db
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  clusterIP: None  

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-initdb-scripts
data:
  init.sql: |
    CREATE TABLE IF NOT EXISTS usuarios (
      id INT AUTO_INCREMENT PRIMARY KEY,
      nombre VARCHAR(100) NOT NULL,
      contraseña VARCHAR(100) NOT NULL
    );

    INSERT INTO usuarios (nombre, contraseña) VALUES
      ('hamza', '1234'),
      ('clase', 'abcd');


