/*
SQLyog Trial v13.1.9 (64 bit)
MySQL - 10.4.28-MariaDB : Database - almacen
*********************************************************************
*/

/*!40101 SET NAMES utf8 */;

/*!40101 SET SQL_MODE=''*/;

/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;
CREATE DATABASE /*!32312 IF NOT EXISTS*/`almacen` /*!40100 DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci */;

USE `almacen`;

/*Table structure for table `almacen` */

DROP TABLE IF EXISTS `almacen`;

CREATE TABLE `almacen` (
  `PRODUCTO` varchar(255) DEFAULT NULL,
  `PRECIO` double DEFAULT NULL,
  `ALMACEN` varchar(255) DEFAULT NULL,
  `CODIGO` varchar(255) NOT NULL,
  `EXISTENCIAS` double DEFAULT NULL,
  PRIMARY KEY (`CODIGO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;

/*Data for the table `almacen` */

insert  into `almacen`(`PRODUCTO`,`PRECIO`,`ALMACEN`,`CODIGO`,`EXISTENCIAS`) values 
('Placabase',140,'CORDOBA','CH 23',12),
('LENTE VARIFOCAL 6 A 60 MM F1.6 ',14,'Malaga','CM 4',72),
('LENTE VARIFOCAL 3,5 A 8 MM F1.4 AUTOIRIS ',6,'Malaga','CM 5',22),
('LENTE VARIFOCAL 6 A 60 MM F1.6 AUTOIRIS ',5,'Malaga','CM 6',20),
('LENTE CS VARIFOCAL 2,8 A 12 MM F1.4 AUTOIRIS ',10,'Malaga','CM 7',45),
('SOPORTE ALUMINIO PARA CAMARA CCTV GRAFITO ',11,'Cordoba','CM 8',13),
('SOPORTE ALUMINIO PARA CAMARA CCTV PLATA ',6,'Cordoba','CM 9',5),
('Papel',12,'CORDOBA','CO34',34),
('ADAPTADOR DE DISCO SATA A DISCO IDE ',5,'Granada','HF 11',67),
('DISCO DURO 250GB SATA PARA SERVIDOR WEB ',8,'Granada','HF 12',17),
('DISCO DURO 500GB SATA PARA SERVIDOR WEB ',5,'Granada','HF 13',5),
('SECUENCIADOR PARA 8 CAMARAS ',11,'Sevilla','HF 2',34),
('SECUENCIADOR 8 CAMARAS CON AUDIO ',11,'Sevilla','HF 3',34),
('SECUENCIADOR 8 CAMARAS CON ALARMA ',10,'Sevilla','HF 4',15),
('CONVERTIDOR DE VIDEO A VGA ',13,'Sevilla','HF 5',15),
('GRABADORA DIGITAL 36 HORAS USB ',5,'Granada','HF 6',72),
('GRABADOR DIGITAL VIDEO 4 CANALES BASICO ',6,'Granada','HF 7',89),
('GRABADOR DIGITAL 4 CANALES H264 CON RED ',13,'Granada','HF 8',43),
('GRABADOR DIGITAL 8 CANALES H264 CON RED ',14,'Granada','HF 9',24),
('LENTE FIJA 6 MM TIPO BOARD  ',7,'Malaga','MP 1',2),
('LENTE FIJA 8 MM TIPO BOARD ',7,'Malaga','MP 2',61),
('LENTE FIJA 12 MM TIPO BOARD ',7,'Malaga','MP 3',97),
('LENTE FIJA 16 MM TIPO BOARD ',5,'Malaga','MP 4',12),
('LENTE AUTOIRIS GRAN ANGULAR 2,8 MM 1/3 ',7,'Malaga','MP 5',87),
('LENTE AUTOIRIS 4 MM 1/3 ',9,'Malaga','MP 6',12),
('LENTE AUTOIRIS 6 MM 1/3 ',7,'Malaga','MP 7',76),
('LENTE AUTOIRIS 8 MM 1/3 ',14,'Malaga','MP 8',80),
('LENTE AUTOIRIS 12 MM 1/3  ',7,'Malaga','MP 9',81),
('DISCO DURO 1000GB SATA PARA SERVIDOR WEB ',7,'Granada','PO 1',97),
('MINICAMARA ESPIA OCULTA EN AURICULAR CABLEADA ',11,'Granada','PO 2',78),
('MINICAMARA ESPIA OCULTA LENTE BOTON CABLEADA ',7,'Granada','PO 3',26),
('MINI CAMARA ESPIA OCULTA LENTE TORNILLO CABLEADA ',12,'Granada','PO 4',93),
('MINICAMARA ESPIA OCULTA LENTE PINHOLE CABLEADA ',7,'Granada','PO 5',38),
('MINICAMARA ESPIA OCULTA EN BOTON INALAMBRICA ',12,'Granada','PO 6',69),
('TRANSMISOR INALAMBRICO PARA CAMARA ESPIA 500 MW ',8,'Granada','PO 7',45),
('CAMARA DOMO SIMULADA CON PRESENCIA ',11,'Cordoba','VC 1',52),
('CAMARA COLOR INFRARROJOS EXTERIOR CON ZOOM X22 80M ',8,'Sevilla','VC 10',99),
('CAMARA MICROSCOPIO CON CONEXIÓN USB  ',8,'Sevilla','VC 11',93),
('TELEVISION MONITOR LCD COLOR 7 PULGADAS ',9,'Sevilla','VC 12',22),
('TELEVISION MONITOR LCD EN PARASOL 5,6 PULGADAS PILOTO ',10,'Sevilla','VC 13',58),
('MONITOR LCD EN PARASOL 5,6 PULGADAS COPILOTO ',12,'Sevilla','VC 14',62),
('MONITOR COLOR SECUENCIADOR 4 CAMARAS ',8,'Sevilla','VC 15',28),
('QUAD COLOR 8 CAMARAS CON MENU Y OSD ',5,'Sevilla','VC 16',92),
('CAMARA COLOR INFRARROJOS ANTIVANDALICA VARIFOCAL 30 M ',10,'Cordoba','VC 2',42),
('CAMARA COLOR EXTERIOR VISION NOCTURNA 30M LENTE 6 MM ',6,'Sevilla','VC 3',32),
('CAMARA COLOR DIA NOCHE ALTA RESOLUCION CON SONIDO ',11,'Sevilla','VC 4',2),
('CAMARA DIA NOCHE ALTA RESOLUCION Y SENSIBILIDAD ',12,'Sevilla','VC 5',94),
('CAMARA EXTERIOR VISION NOCTURNA ALTA RESOLUCION 50M ',8,'Sevilla','VC 6',47),
('CAMARA COLOR EXTERIOR VISION NOCTURNA 75M ',14,'Sevilla','VC 7',72),
('CAMARA COLOR EXTERIOR VISION NOCTURNA 100M ',8,'Sevilla','VC 8',72),
('CAMARA COLOR EXTERIOR VISION NOCTURNA CON VISERA 15 METROS ',15,'Sevilla','VC 9',15);

/*Table structure for table `alumnos` */

DROP TABLE IF EXISTS `alumnos`;

CREATE TABLE `alumnos` (
  `nombre` varchar(20) DEFAULT NULL,
  `dni` varchar(10) NOT NULL,
  PRIMARY KEY (`dni`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;

/*Data for the table `alumnos` */

insert  into `alumnos`(`nombre`,`dni`) values 
('Luis','2452345'),
('Antonio Sanchez','30456892J'),
('matriz[0]','matriz[1]');

/*Table structure for table `datos` */

DROP TABLE IF EXISTS `datos`;

CREATE TABLE `datos` (
  `primero` varchar(20) DEFAULT NULL,
  `segundo` int(5) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;

/*Data for the table `datos` */

insert  into `datos`(`primero`,`segundo`) values 
('antonio',0),
('manuel',1235456);

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;
