name: "CI/CD Service"
on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      entornos:
        description: "¿En que entorno quieres desplegarlo?"
        required: true
        default: development
        type: choice
        options:
          - development
          - production

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar Repositorio
        uses: actions/checkout@v2
      - name: Establecer Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login Docker-Hub
        uses: docker/login-action@v2
        with: 
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Crear y Publicar PHP web image
        run: |
          docker compose -f docker-compose.yml build web
          docker tag mi-appweb:latest khalifi11/mi-appweb:latest
          docker push khalifi11/mi-appweb:latest
  
  deploy-dev:
      if: github.ref == 'refs/heads/main' || (github.event_name == 'workflow_dispatch' && github.event.inputs.entornos == 'development')
      needs: build
      runs-on: [self-hosted, windows]
      steps:
        - name: Clonar repositorio
          uses: actions/checkout@v2
        - name: Aplicar deployment con kubectl
          run: |
            kubectl apply -f ./k8s/deployment.yml
        
  deploy-prod:
    if: github.ref == 'refs/heads/main' || (github.event_name == 'workflow_dispatch' && github.event.inputs.entornos == 'production')
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Copiar docker-compose al servidor
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          source: "docker-compose.yml"
          target: "/home/${{ secrets.SSH_USER }}/mi-app/"

      - name: Hacer deploy remoto vía SSH
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd mi-app
            docker pull khalifi11/mi-appweb:latest
            docker compose down
            docker compose up -d
        
