name: "CI/CD Service"
on:
  workflow_dispatch:
    inputs:
      entornos:
        description: "¿En que entorno quieres desplegarlo?"
        required: true
        default: development
        type: choice
        options:
          - development
          - production

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar Repositorio
        uses: actions/checkout@v2
      - name: Establecer Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login Docker-Hub
        uses: docker/login-action@v2
        with: 
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Crear y Publicar PHP web image
        run: |
          docker compose -f docker-compose.yml build web
          docker tag mi-appweb:latest khalifi11/mi-appweb:latest
          docker push khalifi11/mi-appweb:latest
  
  deploy-dev:
      if: github.ref == 'refs/heads/main' || (github.event_name == 'workflow_dispatch' && github.event.inputs.entornos == 'development')
      needs: build
      runs-on: [self-hosted, windows]
      steps:
        - name: Clonar repositorio
          uses: actions/checkout@v2
        - name: Aplicar deployment con kubectl
          run: |
            kubectl apply -f ./k8s/deployment.yml
        
  deploy-prod:
      if: github.ref == 'refs/heads/main' || (github.event_name == 'workflow_dispatch' && github.event.inputs.entornos == 'production')
      needs: build
      runs-on: ubuntu-latest
      steps:
        - name: Desplegar en EC2 con Docker Compose
          uses: appleboy/ssh-action@v0.1.7
          with:
            host: ${{ secrets.EC2_HOST }}
            username: ${{ secrets.HOST }}
            key: ${{ secrets.SSH_KEY }}
            script: |
                sudo apt update
                sudo apt install -y git docker.io docker-compose-plugin
                sudo systemctl enable docker
                sudo systemctl start docker
                sudo usermod -aG docker $USER

                if [ ! -d "mi-app" ]; then
                git clone https://github.com/${{ github.repository }} mi-app
                fi
          
                cd mi-app
                git reset --hard
                git pull origin main

                docker pull khalifi11/mi-appweb:latest
                docker compose down || true
                docker compose up -d
        
